### ISSUE TITLE
[RELEASE-CHECKLIST] GEOS-Chem 12.9.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#341]
# Checklist for releasing GEOS-Chem 12.9.0

## Benchmarks

The following benchmark simulations are needed to validate this version (edit as needed). For items marked at complete, benchmark simulations have finished, benchmark plots have been created and posted on the FTP site, and benchmark information has been posted on the GEOS-Chem wiki.

- [x] GEOS-Chem classic benchmarks:
  - [x] Full unit test
  - [x] 1-month full-chemistry benchmark
  - [x] 1-year full-chemistry benchmark
      - [ ] Archive PCO and PCH4 fields for tagged CO simulations in `ExtData/HEMCO/TAGGED_CO/`
      - [x] Archive restart files in `ExtData/GEOSCHEM_RESTARTS/`
- [x] GCHP benchmarks:
  - [x] 1-month full-chemistry benchmark
- [x] Send benchmarks to developers and GCSC for approval

## Github repositories
- [x] Push tags for this version to all repositories:
  - [x] https://github.com/geoschem/geos-chem
  - [x] https://github.com/geoschem/gchp
  - [x] https://github.com/geoschem/geos-chem-unittest
- [x] Publish new GEOS-Chem release on Github

## Data
- [x] Document updated data directories for current version on wiki
- [x] Copy updated data files to Compute Canada

## Wiki and website updates
- [x] Update [Species in GEOS-Chem](http://wiki.seas.harvard.edu/geos-chem/index.php/Species_in_GEOS-Chem)
- [x] Update version number on the following pages:
  - [x] [GEOS-Chem website](http://acmg.seas.harvard.edu/geos/)
  - [x] [GEOS-Chem wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/Main_Page)
  - [x] [GEOS-Chem versions](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_versions)
  - [x] [GEOS-Chem 12](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12#Version_history_summary)

- [ ] Send email to user list announcing release
