### ISSUE TITLE
[RELEASE-CHECKLIST] GEOS-Chem 13.0.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#342]
# Checklist for releasing GEOS-Chem 13.0.0

## Benchmarks

The following benchmark simulations are needed to validate this version (edit as needed). For items marked at complete, benchmark simulations have finished, benchmark plots have been created and posted on the FTP site, and benchmark information has been posted on the GEOS-Chem wiki.

- [x] GEOS-Chem classic benchmarks:
  - [x] Integration tests
  - [x] 1-month full-chemistry benchmarks
    - [x] Update default compiler to IFORT 18
    - [x] July 2016 with GEOS-FP
    - [x] July 2016 with MERRA-2
    - [x] July 2019 with MERRA-2 **(New default for 1-month benchmarks)**
    - [x] New tropchem simulation
      - This simulation will use the "Standard" chemistry mechanism in troposphere and archived prod/loss rates in the stratosphere (obtained from 10-year run below)
  - [x] 1-year full-chemistry benchmark (2019, 4x5, MERRA-2) 
  - [x] 1-year Transport Tracer benchmark     
  - [x] 10-year benchmark simulation to evaluate stratosphere (2010-2019, 4x5, MERRA-2)
    - [x] Archive monthly mean species concentrations for all 10 years (3/3/21: Files can be found in `ExtData/HEMCO/GCClassic_Output/13.0.0/`)
      - [x] Update all specialty simulations to use these OH fields by default
    - [x] Archive monthly P/L rates (3/3/21: Files can be found in `ExtData/HEMCO/GCClassic_Output/13.0.0/`)
    - [x] Archive PCO and PCH4 fields for tagged CO simulations (3/3/21: Files can be found in `ExtData/HEMCO/GCClassic_Output/13.0.0/`)
    - [x] Archive restart files in `ExtData/GEOSCHEM_RESTARTS/`

- [x] GCHP benchmarks:
  - [x] Integration tests 
  - [x] 1-month full-chemistry benchmark
  - [x] 1-year full-chemistry benchmark
  - [x] 1-year Transport Tracer benchmark
  - [x] 10-year Stratospheric benchmark (2010-2019, c48, MERRA-2)

## Github repositories
- [x] Update the MIT License files (AUTHORS.txt and LICENSE.txt) in all repositories:
  - [x] https://github.com/geoschem/GCClassic
  - [x] https://github.com/geoschem/geos-chem
  - [x] https://github.com/geoschem/GCHP
  - [x] https://github.com/geoschem/HEMCO (version 3.0.0)
  - [x] https://github.com/geoschem/gcpy (version 1.0.0)
- [x] Push tags for this version to all repositories:
  - [x] https://github.com/geoschem/GCClassic (new wrapper)
  - [x] https://github.com/geoschem/geos-chem
  - [x] https://github.com/geoschem/GCHP
  - [x] https://github.com/geoschem/HEMCO (version 3.0.0)
  - [x] https://github.com/geoschem/gcpy (version 1.0.0)
- [x] Update the README.md file in all repositories -- note that the "master" branch is now "main", etc.
  - [x] https://github.com/geoschem/GCClassic
  - [x] https://github.com/geoschem/geos-chem
  - [x] https://github.com/geoschem/GCHPctm 
  - [x] https://github.com/geoschem/HEMCO (version 3.0.0)
  - [x] https://github.com/geoschem/gcpy (version 1.0.0)
 - [x] Make clear the following repositories will be retired
    - https://github.com/geoschem/geos-chem-unittest
    - https://github.com/geoschem/gchp
- [x] Publish new releases on Github

## Data
- [x] Update default restart files used for full-chemistry simulations
- [x] Document updated data directories for current version on wiki
- [x] Copy updated data files to Compute Canada
- [x] Create AMI for GEOS-Chem Classic 13.0.0

## Wiki and website updates
- [x] Update version number on the following pages:
  - [x] [GEOS-Chem website](http://acmg.seas.harvard.edu/geos/)
  - [x] [GEOS-Chem wiki](http://wiki.seas.harvard.edu/geos-chem/index.php/Main_Page)
  - [x] [GEOS-Chem versions](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_versions)
  - [x] [GEOS-Chem 12](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12)

## YouTube tutorials

- [x] Getting started with GEOS-Chem Classic 13.0.0
- [x] Getting started with GCHP 13.0.0
- [x] Getting started with HEMCO 3.0.0 (standalone)
- [x] Getting started with GCPy 1.0.0

## Announcement
 
- [x] Send newsletter announcing the release of GEOS-Chem 13.0.0-rc
